### ISSUE TITLE
How to suppress "Invalid date/time in zip entry" warning?

### ISSUE THREAD

**Issue by bronson** [rubyzip/rubyzip#112]
rubyzip inserts this error in the logs every time I open a kmz file.  I have no control over the input files and I'm not sure I'd worry about an invalid date even if I did.

Is there any way to suppress this message?

It looks like it's generated by a puts call: https://github.com/rubyzip/rubyzip/blob/3917dedbb5bf92db71e1804ea2e8dbac3d2891dd/lib/zip/entry.rb#L557

Thanks!

**Comment by dogweather** [comment]
:+1: Same here.

**Comment by ShockwaveNN** [comment]
@simonoff I think you can close this issue

**Comment by audionerd** [comment]
For anyone visiting who still experiences this issue, the fix by @ShockwaveNN is to upgrade to Rubyzip 1.1.7 and add:

`Zip.warn_invalid_date = false`

**Comment by zako42** [comment]
We experienced this issue because we were stubbing the to_binary_dos_date and returning 0.  However 0 is not a valid value that parse_binary_dos_format expects.  You can calculate a valid number by following the method [to_binary_dos_date](https://github.com/rubyzip/rubyzip/blob/04714ece9ace041b00e0c292b200cb8c32660476/lib/zip/dos_time.rb#L21).  For example, for Dec 1, 2015, you would use 18305.  Return a valid value and you won't get the warning messages.

**Comment by amias-channer** [comment]
the Zip.warn_invalid_date = false solution also works for zip-zip
