### ISSUE TITLE
StringIO

### ISSUE THREAD

**Issue by simonoff** [rubyzip/rubyzip#18]
Anyone want StringIO support?

**Comment by Paxa** [comment]
How to use it?

**Comment by simonoff** [comment]
@Paxa instead of path to file you provides StringIO instance.

**Comment by jasonperrone** [comment]
I am wondering why I cannot get this to work? 
I have a String which is a zip file I retrieved via REST. This String is a valid zip file because if I IO.binwrite it to a file, I can unzip with RubyZip. 

So, I did this:
s = my String containing the zip file data

```
stringio = StringIO.new(s)
z = Zip::InputStream.new(stringio) => <Zip::InputStream:0x00005583d34157d8 @lineno=0, @pos=0, @output_buffer="", @archive_io=#<StringIO:0x00005583d34156e8>, @decompressor=Zip::NullDecompressor, @decrypter=#<Zip::NullDecrypter:0x00005583d3415698>, @current_entry=nil> 

```

as you can see, ZipInputStream sees it as null.
zipinputstream.entries => []

Any thoughts?

**Comment by elcortez** [comment]
@simonoff please, can you tell me how exactly it works ? Whenever I put a StringIO Instance, I get the following error 
`no implicit conversion of StringIO into String` 
I took the code directly from the documentation
Zip::File.open(filename, create: true) do |zipfile|

**Comment by hainesr** [comment]
Hi @elcortez, `File#add` is for adding files to an archive (which might be a StringIO) directly from the local filesystem (at the moment at least). You can add the contents of a StringIO to an archive by opening an output stream to an entry with `File#get_output_stream` and copying it in through that.
