### ISSUE TITLE
ZipInputStream broken (same as issue #30)

### ISSUE THREAD

**Issue by amilligan** [rubyzip/rubyzip#221]
Opening a zip archive with a Zip::InputStream still returns only one entry, no matter the number of files in the archive.  Issue #30 described this; it was recently closed, but the problem remains.

**Comment by simonoff** [comment]
Hm... Still can you attach zip file what you cannot view?

I tested with xlsx file and all works fine

```rb
ruby 2.2.0: main
>> Zip::InputStream::open("test.xlsx") do |io|
 >     while (entry = io.get_next_entry) do
 >       pp entry.name
 >     end
 >   end
"[Content_Types].xml"
"_rels/.rels"
"xl/_rels/workbook.xml.rels"
"xl/workbook.xml"
"xl/sharedStrings.xml"
"xl/styles.xml"
"xl/theme/theme1.xml"
"xl/worksheets/_rels/sheet1.xml.rels"
"xl/worksheets/sheet1.xml"
```

**Comment by amilligan** [comment]
The archive I'm working with is too large to attach, unfortunately; here's a link to it: http://bdn-ak.bloomberg.com/precanned/Equity_Common_Stock_20150216.txt.zip

**Comment by simonoff** [comment]
Notice about ::Zip::InputStream

::Zip::InputStream usable for fast reading zip file content because it not read Central directory.

But there is one exception when it not working - General Purpose Flag Bit 3.

If bit 3 (0x08) of the general-purpose flags field is set, then the CRC-32 and file sizes are not known when the header is written. The fields in the local header are filled with zero, and the CRC-32 and size are appended in a 12-byte structure (optionally preceded by a 4-byte signature) immediately after the compressed data
If ::Zip::InputStream will found such entry in zip archive it will raise exception.

**Comment by njakobsen** [comment]
I have this same problem. I just zipped some files in OS X and it only returns the first one when iterating using `get_next_entry`.

**Comment by cattywampus** [comment]
I also just tested this with 1.1.7 and I am only reading the first entry when I use the `Zip::InputStream#open` call. What's interesting is it works fine when I use `Zip::File#open`, however that's not ideal since the zip data is in memory and not on disk for my situation.
