### ISSUE TITLE
Files in zipe corrupted on windows

### ISSUE THREAD

**Issue by jdkealy** [rubyzip/rubyzip#246]
Hi, 

I'm generating zips with rubyzip. I posted an issue yesterday where clients couldn't extract the zips. I upgraded to the latest rubyzip, but windows clients are now saying that they can extract the zips, but it's saying that the contents (images) of the zip are corrupted. 

    Zip::File.open(zip_path, Zip::File::CREATE) do |zipfile|
      names = []
      photo_paths.each do |path|
        photo_filename = path.split('/').last
        event_id       = photo_filename.split(".").first.split("_")[1]
        photo_id       = photo_filename.split(".").first.split("_").last
        photo_filename = "nc_#{event_id}_#{photo_id}#{File.extname(path)}"
        zipfile.add(photo_filename, path)
      end
    end

Has anyone run into these issues before ? Works fine for mac users and the files themselves, I can send one by one.

**Comment by jdkealy** [comment]
sorry i had this complaint from a client, could not reproduce

**Comment by daltonrenaldo** [comment]
I am currently having this issue right now. Everything works file on macOS, but on Windows complaints that  the zip is invalid. I try winwar, and was able to unzip certain files, but not all of them; and still got a message the the zip is corrupt.

At first I thought it could be because of non-ascii filenames, but was not the case; I still ensure ```Zip.unicode_names = true``` was set, but that did not resolve the problem.
