### ISSUE TITLE
Zip::OutputStream.write_buffer doesn't work with Tempfiles

### ISSUE THREAD

**Issue by jhulford** [rubyzip/rubyzip#265]
Trying to write a zip directly to a File IO object doesn't work...the docs indicate it should.

I believe the following extremely simplified code should work:

``` ruby
File.open("file.zip", "wb") do |temp|
  Zip::OutputStream.write_buffer(temp) do |os|
    os.put_next_entry("test.txt")
    File.open("test.txt", "rb") do |infile|
      os.write(infile.read(1024)) until infile.eof?
    end
  end
  temp.flush
  FileUtils.cp temp.path, "/another/path/file.zip"
end
```

The resulting file.zip ends up being several bytes short of what it should be and unable to be opened.

It appears that Zip::OutputStream monkeys with the IO object in it's constructor for some reason, dup'ing it, reopening and rewinding it for some reason.  The dup call seems to be what's causing the issue here.

I'm not sure why the constructor is doing this (something internal to zip?).  In general, I think it's pretty much expected if you're passing a stream into a method that the method is going to write to the stream at the current write cursor point.  In my case, that's exactly what I want to happen.

I can work around, by reimplementing dup, reopen and rewind on my file handle, but I don't think I should really have to.

**Comment by danielfone** [comment]
@jhulford no doubt you're long since past this, but I'll leave this here for posterity.

As you rightly note, Zip::OutputStream `dup`s the output stream it's given. Because of this, its internal copy can get out of sync with the original one. It is the **internal** stream that needs to be flushed. In this example, it'd look something like:

```
zip = Zip::OutputStream.write_buffer(temp) do |os|
  # …
end
zip.flush
# At this point, all the buffers should be in sync and can be safely closed.
```

I suspect this issue only manifests with TempFiles because they're often copied off the disk before the internal buffer is properly flushed and closed.

**Comment by jhulford** [comment]
Thanks for the update - it's good to know for future reference.  I actually worked around this at the time by just using the OutputStream#open method on the tempfile's path I was writing to, rather than trying to write directly to the file handle with write_buffer.

**Comment by dmolesUC** [comment]
I had the same thing happen with a plain file in a test:

```ruby
Dir.mktmpdir('test') do |dir|
  output_path = File.join(dir, 'out.zip')
  File.open(output_path, 'wb') do |f|
    Zip::OutputStream.write_buffer(f) do |stream|
      # put some entries, write some data...
    end
  end

  # call some code that tries to read the file
  # => read fails with 'end of central directory signature not found'
end
```

Based on the comments above, I was able to work around this with 

```ruby
    zip = Zip::OutputStream.write_buffer(f) do |stream|
      # put some entries, write some data...
    end
    zip.flush
```

But I still don't understand:

1. why `Zip::OutputStream` dups/reopens/rewinds the stream it's given
2. why (if it has to do that) `write_buffer` doesn't flush before returning

**Comment by hainesr** [comment]
I also don't understand why we dup, reopen and rewind the stream... I've looked at the blame and it appears to have been added 7/8 years ago and I've still not really got to the bottom of why. We don't dup under Windows, BTW, as that causes other issues, and it seems it's not needed. Anyway, if I comment out the dup, reopen and rewind the entire test suite passes, so... um. Dunno. I need to think more before I just rip it out 😄 Maybe whatever the underlying reason for the dup, repoen and rewind was has been fixed elsewhere...

On the subject of flushing though, presumably that's safe to do as we close the stream anyway, so we probably just should do it, right?

**Comment by danielfone** [comment]
@hainesr I'm not working on projects with this functionality anymore, but if you want me to test a PR, I'll see if I can dig them out and let you know how it goes.

**Comment by hainesr** [comment]
Thanks @danielfone. I decided to simply flush for now as it seemed safest. If you have the opportunity to test HEAD, that would be great, thanks!

**Comment by danielfone** [comment]
@hainesr finally shaved the yak and got the old project going again today. The good news is that this change fixes the described issue in the codebase I tested. 🎉 

The bad news is that an unrelated change (https://github.com/rubyzip/rubyzip/commit/5af76cecb51e618ded61bba7a9e4078b4df7b921) introduces a regression in the same project. The short story is that I can't use `IO.copy_stream` on the `Zip::OutputStream` anymore. If I remove the `Zlib::SYNC_FLUSH` it works fine.

Personally, I'm not worried about this because it's a dead project. If you like though I can open an issue for the regression. Up to you. 😄

**Comment by hainesr** [comment]
Hi @danielfone, thank you for checking this, and great that we've fixed at least something.

I've tried doing a couple of tests with `IO.copy_stream` into a `Zip::OutputStream` for an entry, but can't replicate a failure. There are so many ways of mixing and matching the various streams, etc. It would be really useful if you could open a new issue with specific details of what's not working for you, please.

Many thanks!

**Comment by danielfone** [comment]
@hainesr I've chased this down this morning and can report the issue was not with rubyzip!

FWIW, it turns out the source IO mock in the tests didn't implement `#read` properly. Specifically, in the case where the stream was at EOF/EOS and `#read(positive_integer)` was called (via `IO.copy_stream`), the IO object was returning `""` instead of `nil`. It was this empty string that was causing the `Zlib::BufError`, but only when `Zlib::SYNC_FLUSH` is also enabled. That was a fun bug to find. 😅

**Comment by hainesr** [comment]
Great, thanks for the update @danielfone.

I'm still wary of why we need the `Zlib::SYNC_FLUSH` - the commit that added it mentions JRuby, but I've tested with a (sort of) up-to-date version and it seems OK. I guess I'll leave it for now and keep an eye on it.

Thanks again!
