### ISSUE TITLE
unzip issue for files greater than 4GB

### ISSUE THREAD

**Issue by sg191194** [rubyzip/rubyzip#348]
error: file #49683:  bad zipfile offset (local header sig):  167800
  (attempting to re-compensate)

**Comment by jasonperrone** [comment]
why was this closed? We're seeing the same problem.

**Comment by gregogalante** [comment]
I'm getting the same error with zip of 10-11GB size

**Comment by miguelalcalde** [comment]
@bv-shubham did this issue get solved for you at any point? any other useful info? I'm getting an error unzipping through java lib.

**Comment by hainesr** [comment]
When zipping large files with rubyzip you need to turn on Zip64 support: `Zip.write_zip64_support = true`.

If you haven't been doing this, can you try and see if it helps?

**Comment by singlewind** [comment]
The zip64 was working for file size like 11-20GB. The error show up again on 20GB+ file.

**Comment by hainesr** [comment]
Hi @singlewind,

A few questions to help narrow down your issue:
* Are you zipping or unzipping with rubyzip?
* Which version of rubyzip are you using?
* If you are zipping with rubyzip, have you set `Zip.write_zip64_support = true` before using any rubyzip operations?

If you are unzipping then I will have more, different, questions 😄

**Comment by singlewind** [comment]
We are using rubyzip (2.3.2). We are using other unzip tools to verify the zip files zipped by rubyzip. We were have issue for a single file larger than 4GB. After we added `Zip.write_zip64_support  = true`, the problem was resolved. Then we found it failed on a larger file around 18GB.
 
Below is our config
```
require 'zip'

Zip.setup do |config|
  config.continue_on_exists_proc = true
  config.unicode_names = true
  config.default_compression = Zlib::BEST_COMPRESSION
  config.write_zip64_support = true
end
```

**Comment by hainesr** [comment]
Thanks. More questions, sorry:

* Are you storing huge files in your archives? Or huge _numbers_ of files? Or both?
* Are you creating archives from scratch, or are you working with (adding/removing files to/from) existing archives when you see failures?
* Please could you provide the output of the tool that you are verifying with, so that I can see the error?
* Is there any chance you could provide a minimal code example that fails?

Many thanks!

**Comment by singlewind** [comment]
Are you storing huge files in your archives? Or huge numbers of files? Or both?
Yes, each archive only contains one big xml file.

Are you creating archives from scratch, or are you working with (adding/removing files to/from) existing archives when you see failures?
Yes, create from scratch.

Please could you provide the output of the tool that you are verifying with, so that I can see the error?
Zip 3.0 (July 5th 2008)

Is there any chance you could provide a minimal code example that fails?
Beside the setup in the last post, here is the function does the the compress.
```ruby
  def zip(file)
    return unless file and File.exist? file

    zip_filename(file).tap do |zip_file|
      ::Zip::File.open(zip_file, ::Zip::File::CREATE) { |zf| zf.add(File.basename(file), file) }
    end
  end
```

**Comment by hainesr** [comment]
Thanks. For the tool output, sorry, I meant please could you share the entire output of the tool when you verify one of your broken files? I'd like to see the full error text. Thanks
