### ISSUE TITLE
Path traversal vulnerability

### ISSUE THREAD

**Issue by mramydnei** [rubyzip/rubyzip#354]
# Overview
Rubyzip module is vulnerable to path traversal in windows environment.Unzip a zip file which contains a file with directory traversal characters in their embedded path will extract the contaied file to unexpected directory.

# POC

## 1. Create a zip file which contains a file with `..\` characters

```
$ git clone https://github.com/ptoomey3/evilarc.git
$ cd evilarc/
$ python evilarc.py 1.txt -d 1
Creating evil.zip containing ..\1.txt
```

## 2. Extract evil.zip with rubyzip

test.rb
```
require 'zip'

Zip::File.open('evil.zip') do |zip_file|
  # Handle entries one by one
  zip_file.each do |entry|
    # Extract to file/directory/symlink
    puts "Extracting #{entry.name}"
    entry.extract(entry.name)
  end
end
```

```
C:\Users\test\Desktop>ruby test.rb
Extracting ..\1.txt

C:\Users\test\Desktop>cd ..

C:\Users\test>dir
 Volume in drive C has no label.
 Volume Serial Number is E0CE-337D

 Directory of C:\Users\test

02/23/2018  05:04 PM    <DIR>          .
02/23/2018  05:04 PM    <DIR>          ..
02/23/2018  05:04 PM                 4 1.txt
09/15/2017  01:31 PM    <DIR>          Contacts
02/23/2018  05:03 PM    <DIR>          Desktop
09/15/2017  01:31 PM    <DIR>          Documents
02/23/2018  04:04 PM    <DIR>          Downloads
09/15/2017  01:31 PM    <DIR>          Favorites
09/15/2017  01:31 PM    <DIR>          Links
09/15/2017  01:31 PM    <DIR>          Music
09/15/2017  01:31 PM    <DIR>          Pictures
09/15/2017  01:31 PM    <DIR>          Saved Games
09/15/2017  01:31 PM    <DIR>          Searches
09/15/2017  01:31 PM    <DIR>          Videos
               2 File(s)             16 bytes
              14 Dir(s)  117,918,547,968 bytes free

C:\Users\test>
```
# Enviroment

```
C:\Users\test>ver
Microsoft Windows [Version 6.1.7601]

C:\Users\test>ruby -v
ruby 2.5.0p0 (2017-12-25 revision 61468) [i386-mingw32]

C:\Users\test>gem list rubyzip
*** LOCAL GEMS ***
rubyzip (1.2.1)
```

**Comment by attritionorg** [comment]
Similar to https://github.com/rubyzip/rubyzip/issues/315

**Comment by mramydnei** [comment]
Any updates?

**Comment by simonoff** [comment]
@mramydnei i don't have a windows to test. Can you provide a PR for fix?

**Comment by hainesr** [comment]
There is an interesting interaction between this issue and #308 (where conversion of `\`s in filenames to `/`s was removed to fix an encoding bug), but has since caused #324.

A file named `..\1.txt` will - in Linux at least - be extracted to the *current directory* with the literal name `'..\1.txt'` using the code snippet above. This is because this line - `entry.extract(entry.name)` bypasses part of the security check by passing in the bad name.

I think I know how to fix all this. I'll work up a PR.

**Comment by hainesr** [comment]
More things, now I look at this again:

- It seems that dealing with #324 makes this issue no-longer Windows-only.
- Calling `entry.extract` is safe because the entry name stored in the zipfile is checked for `..`, etc. There are tests to prove/ensure this in `test/path_traversal_test.rb`.
- Calling `entry.extract(a_name)` allows for `a_name` to include `..`, etc, but only at the behest of the user/dev.

The question that the last point raises is: is this a bug? So long as files are not accidentally extracted to relative paths (from, say, a malicious zipfile) shouldn't the user of this library be able to specify any path they like for extraction?

**Comment by hainesr** [comment]
I have thought on this a bit, and checked the docs, and I don't think this is a bug. The doc comment for `extract` clearly says:
```ruby
# Extracts entry to file dest_path (defaults to @name).
# NB: The caller is responsible for making sure dest_path is safe, if it
# is passed.
def extract(dest_path = nil, &block)
```
So we do check that an entry name is safe before extracting, but the user of `extract` must be careful if supplying `dest_path`.
