### ISSUE TITLE
Changelog is missing the details about the 1.2.2 release

### ISSUE THREAD

**Issue by opsidao** [rubyzip/rubyzip#378]
Title says it all, there are no details on the Changelog about what changes were included in the 1.2.2 release.

Thanks!

**Comment by aspiers** [comment]
Also observed in [this comment](https://github.com/rubyzip/rubyzip/commit/fd81bd523cd53096c1a1dce1e950ef0b7658a02c#commitcomment-30370436).

This is particularly unfortunate because 1.2.2 contains two CVE security fixes, and downstream package-building processes rely on the changelog to keep track of when security vulnerabilities get fixed, e.g. https://build.opensuse.org/package/view_file/devel:languages:ruby:extensions/rubygem-rubyzip/rubygem-rubyzip.changes?expand=1

I've submitted #387 to retroactively add the changelog.
