### ISSUE TITLE
Options not working in File class

### ISSUE THREAD

**Issue by augustocravosilva** [rubyzip/rubyzip#395]
This code
https://github.com/rubyzip/rubyzip/blob/249775f5637e6d65112574b3ac1763dc2393c7f6/lib/zip/file.rb#L88-L89
doesn't do what it is intended to do, because when you pass in `restore_permissions: false` or `restore_times: false`, it will be evaluating to `false || true`, which will always be `true`

**Comment by Amorn-Kingthong** [comment]
i will go

**Comment by hainesr** [comment]
Interestingly the options code doesn't agree with the comments about defaults above either:

https://github.com/rubyzip/rubyzip/blob/94b7fa276992933592d69eb6bb17fc09105f8395/lib/zip/file.rb#L56-L61

vs

https://github.com/rubyzip/rubyzip/blob/94b7fa276992933592d69eb6bb17fc09105f8395/lib/zip/file.rb#L101-L103

I'll cook up a PR that fixes this issue and works as expected to keep the test passing - adjusting the comments as necessary.

**Comment by hainesr** [comment]
Also, depressingly, it doesn't matter what those options are set to; the tests always all pass. I'll add some tests.

**Comment by hainesr** [comment]
So, on further investigation, I don't think that `restore_times: true` can ever work, because I don't think that when you extract a file it ever even attempts to set the timestamp.

As far as I can tell, this is the code which does the actual extraction to a file:
https://github.com/rubyzip/rubyzip/blob/34d2074ecbf6ef8557c29efc03a585c309be5c4b/lib/zip/entry.rb#L597-L624
And there's nothing there that would restore times...

I'm looking at this in more depth.

**Comment by jdleesmiller** [comment]
Sorry, overzealous auto-closing. This is still a problem.
