### ISSUE TITLE
release 1.2.2

### ISSUE THREAD

**Issue by noraj** [rubyzip/rubyzip#396]
Hi,

Please can you add a release with change log for 1.2.2:

![image](https://user-images.githubusercontent.com/16578570/57939565-e60f4c80-78ca-11e9-9bf7-96ce34b18450.png)

I know info is in https://github.com/rubyzip/rubyzip/blob/master/Changelog.md

**Comment by jdleesmiller** [comment]
Thanks for getting in touch.

I was not sure I should retrospectively add release notes for 1.2.2, since I didn't do the release, and it was actually released last year.

However, I have now released 1.2.3 and manually included the changelog entry for 1.2.2 as well, which is hopefully an adequate solution: https://github.com/rubyzip/rubyzip/releases/tag/v1.2.3
