### ISSUE TITLE
Can't read entries in a file

### ISSUE THREAD

**Issue by radiospiel** [rubyzip/rubyzip#417]
I have a zip file (9 GB) which has content (confirmed via `unzip -l`), but rubyzip does not list any of those entries. What am I doing wrong?

This is my code:

```
require "zip"
file_path = "/path/to/file..zip"

Zip::File.open(file_path) do |zip_file|
  zip_file.each do |entry| 
    pp entry
  end
end
```

doesn't print anything.

rubyzip however does detect some entries, as per `@size` and `@total_number_of_entries_in_cdir_on_this_disk`: 

```
Zip::File.open(file_path) do |zip_file|
  pp zip_file
end
```

prints

```
#<Zip::File:0x00007f8c4c0698e0
 @cdir_offset=407345177,
 @comment="",
 @create=false,
 @entry_set=#<Zip::EntrySet:0x00007f8c4c07aed8 @entry_set={}>,
 @file_permissions=33188,
 @name="...",
 @number_of_disk_with_start_of_cdir=0,
 @number_of_this_disk=0,
 @restore_ownership=false,
 @restore_permissions=true,
 @restore_times=true,
 @size=5,
 @size_in_bytes=689,
 @stored_comment="",
 @stored_entries=#<Zip::EntrySet:0x00007f8c4c0780e8 @entry_set={}>,
 @total_number_of_entries_in_cdir_on_this_disk=5>
```

and the 5 entries are matching the content of the zip file (which is 1 directory holding 4 files.)

**Comment by jdleesmiller** [comment]
I'm afraid I don't see anything immediately wrong.

I think the name `total_number_of_entries_in_cdir_on_this_disk` is a bit misleading. It looks like it is coming from [here](https://github.com/rubyzip/rubyzip/blob/8887b703490337f7ab68ebfb4880354db28ba648/lib/zip/central_directory.rb#L106), and [wikipedia describes](https://en.wikipedia.org/wiki/Zip_(file_format)#End_of_central_directory_record_(EOCD)) the content there as "Number of central directory records on this disk", rather than number of entries.

One possible oddity is that `cdir_offset` is only `407345177`, which is much less than 9GB. Is it just one zip file with this problem or all zip files over a certain size? What was the origin of the zip file?

**Comment by radiospiel** [comment]
John, thank yo for your response. As it turns out the files are also invalid as per `unzip(1)`. I am still trying to establish the origin of these, the user claims they were using identical tooling for both valid and invalid files.

I'll keep this ticket uptodate if I find anything, but I think unless I find evidence to the contrary I would close it now.

**Comment by thbar** [comment]
@radiospiel I faced the exact same situation. A file I have is invalid via `unzip`, but reading it with `Zip::File.open_buffer` won't raise an error, won't list any entry, and `total_number_of_entries_in_cdir_on_this_disk` will nonetheless be non-zero (2, which is the actual number of files in the corrupted archive).

By any chance, did you find a way to raise a clear-cut error when an invalid file is met? Thanks!

**Comment by radiospiel** [comment]
@thbar what we figured out in the end is that all those files have been created on MacOS, using the built in compressor. We tried a couple of approaches, and we just couldn't get them to unpack on non-MacOS machines. So we "solved" this by instructing support to tell the users not to use MacOS to build huge zip files.

Such a test could, of course, also be integrated in a website to not allow > 4GB zip uploads for MacOS users.
