### ISSUE TITLE
Zip::InputStreams fails getting entries within a folder

### ISSUE THREAD

**Issue by josearmandojacq** [rubyzip/rubyzip#463]
First, wanted to thank you people for the awesome job you are doing with this project 👏🏽

## Issue

With  a zip following this structure:

```
zip.file
  |
  | -- Test Folder
          |
          | -- file1.mp3
          | -- file2.mp3
          | -- file3.mp3
```

I'm using this code to get the entries:
```
Zip::InputStream.open(tempfile.path) do |io|
        while (entry = io.get_next_entry)
            // do awesome stuffs
        end
      end
```

Unfortunately, `io.get_next_entry` only gets two entries: the name of the folder and randomly one of the .mp3 files.  
I tested it with one zip file without a folder inside and it gets all entries.

Is there a way to make this work?

I'm using ruby v2.6.5 and using rubyzip v2.1.0

**Comment by hainesr** [comment]
Hello and thanks for the issue.

I can't replicate this with rubyzip v2.1.0 or v2.3.0 on Ubuntu 20.04.1. I created a zip in Windows 10 using `7zip` with the same structure as yours, but with pngs instead of mp3s.

A few questions if I may:
* What platform are you on, and which tool created the zip file that is failing to read?
* How big are the mp3s and the zip file in total?
* Can you post the output of `zipinfo` on an example zip file?

For example, the file I created looks like this:
```shell
$ zipinfo folder.zip 
Archive:  folder.zip
Zip file size: 121323 bytes, number of entries: 4
drwx---     6.3 fat        0 bx stor 20-Nov-20 19:51 folder/
-rw-a--     6.3 fat    39363 bx defN 18-Nov-04 09:41 folder/icon-accessible.png
-rw-a--     6.3 fat    34121 bx defN 18-Nov-04 09:41 folder/icon-interoperable.png
-rw-a--     6.3 fat    64026 bx defN 18-Nov-04 09:41 folder/icon-reusable.png
4 files, 137510 bytes uncompressed, 120681 bytes compressed:  12.2%
```

Thanks

**Comment by josearmandojacq** [comment]
Thanks for the reply. I got a hint of what the problem was when you said: 

> using 7zip with the same structure as yours

This is why I deleted the zip file and used a third-party program to create it. And voilà, it worked!!!!

My guess something went wrong while compressing the file with the native macOS utility.

Thanks again 👏🏽
