### ISSUE TITLE
IOError:  not opened for writing

### ISSUE THREAD

**Issue by d-obuchowski** [rubyzip/rubyzip#547]
Hi,
I have a problem with encrypt zip file. I get error like this "IOError:  not opened for writing". If i will remove encryption, everything will work ok. 

I use:
- rubyzip 2.3.2
- ruby 2.7.3
- rails 6.1.7.2

Code: 
```
    Zip::OutputStream.write_buffer(::StringIO.new(''), Zip::TraditionalEncrypter.new('12')) do |output|
      output.put_next_entry(input_file.original_filename) #  here error appears
   end
```

**Comment by hainesr** [comment]
Hi,

Sorry for the delay in responding!

Are you using `frozen_string_literal: true` at the top of your files? If so, then for a `StringIO` to be writeable you should use `StringIO.new(+'')` otherwise the string backing the `StringIO` is frozen and can't be written to. I'm not sure if encryption in particular exposes this behaviour, but thought wise to check if this fixes things for you before going deeper.

**Comment by d-obuchowski** [comment]
Hi, 
Thanks for your response. Yes, the reason of problem was "frozen_string_literal: true".
